### ISSUE TITLE
change the thresholds and icons color

### ISSUE THREAD

**Issue by alakond** [hashashin/OctoPrint-OpiTemp#4]
Hey. Thnx for plugin. How do I change the thresholds, the icon color, or the icon itself?

**Comment by hashashin** [comment]
Hi @alakond.
Right now the "icon" (it's an HTML emoji actually) it's hard coded, you need to look into: 
https://github.com/hashashin/OctoPrint-OpiTemp/blob/master/octoprint_opitemp/static/js/opitemp.js#L14
And if by thresholds you mean refresh interval, it's also hard coded to 10s right now:
https://github.com/hashashin/OctoPrint-OpiTemp/blob/master/octoprint_opitemp/__init__.py#L17
I'll make them configurable and make a new release. Perhaps later today, no promises 😄.

Thanks, salud.

**Comment by alakond** [comment]
No, I thought that you could set thresholds for example
from 0 to 50С - gray icon
from 50 to 55С - yellow icon
from 55 and above - red icon
My icon is this 
<img src="https://habrastorage.org/webt/sw/xn/oo/swxnook_xizrp8uo24rgyjwjc5w.png" />

And on your screenshot like this:
<img src="https://habrastorage.org/webt/x2/gz/c0/x2gzc0zcwkhq8fsdcj5lsmnzyeq.png" />

**Comment by hashashin** [comment]
Oh, I see. That's because different browsers/systems have variations for the same emoji. ex: 
&#127818; <- I see that as my screenshot and you should see it as yours (if you're using the same browser here and with octoprint webui).

Sorry for the misunderstanding... I'll make the changes to make those two variables configurable anyway, emoji html code and refresh rate.

About an actual threshold thingy I've no plans to do that, but it's not a bad idea for future versions, a PR will be welcomed.

**Comment by alakond** [comment]
:) Ok ) Thnx)
